name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libltdl-dev libffi-dev libssl-dev python3-dev zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake
          pip install --upgrade buildozer cython virtualenv

      - name: Build with Buildozer
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: B-Ultra-APK
          path: bin/*.apk
